//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleSocialNetwork.WebUI.PostServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostDto", Namespace="http://schemas.datacontract.org/2004/07/SimpleSocialNetwork.BusinessServices")]
    [System.SerializableAttribute()]
    public partial class PostDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AuthorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatePostedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthorFirstName {
            get {
                return this.AuthorFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorFirstNameField, value) != true)) {
                    this.AuthorFirstNameField = value;
                    this.RaisePropertyChanged("AuthorFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AuthorId {
            get {
                return this.AuthorIdField;
            }
            set {
                if ((this.AuthorIdField.Equals(value) != true)) {
                    this.AuthorIdField = value;
                    this.RaisePropertyChanged("AuthorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthorLastName {
            get {
                return this.AuthorLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorLastNameField, value) != true)) {
                    this.AuthorLastNameField = value;
                    this.RaisePropertyChanged("AuthorLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatePosted {
            get {
                return this.DatePostedField;
            }
            set {
                if ((this.DatePostedField.Equals(value) != true)) {
                    this.DatePostedField = value;
                    this.RaisePropertyChanged("DatePosted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PostServiceReference.IPostService")]
    public interface IPostService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseServiceOf_Post_PostDto/Add", ReplyAction="http://tempuri.org/IBaseServiceOf_Post_PostDto/AddResponse")]
        void Add(SimpleSocialNetwork.WebUI.PostServiceReference.PostDto entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseServiceOf_Post_PostDto/Add", ReplyAction="http://tempuri.org/IBaseServiceOf_Post_PostDto/AddResponse")]
        System.Threading.Tasks.Task AddAsync(SimpleSocialNetwork.WebUI.PostServiceReference.PostDto entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseServiceOf_Post_PostDto/Remove", ReplyAction="http://tempuri.org/IBaseServiceOf_Post_PostDto/RemoveResponse")]
        void Remove(SimpleSocialNetwork.WebUI.PostServiceReference.PostDto entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseServiceOf_Post_PostDto/Remove", ReplyAction="http://tempuri.org/IBaseServiceOf_Post_PostDto/RemoveResponse")]
        System.Threading.Tasks.Task RemoveAsync(SimpleSocialNetwork.WebUI.PostServiceReference.PostDto entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseServiceOf_Post_PostDto/RemoveById", ReplyAction="http://tempuri.org/IBaseServiceOf_Post_PostDto/RemoveByIdResponse")]
        void RemoveById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseServiceOf_Post_PostDto/RemoveById", ReplyAction="http://tempuri.org/IBaseServiceOf_Post_PostDto/RemoveByIdResponse")]
        System.Threading.Tasks.Task RemoveByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseServiceOf_Post_PostDto/Update", ReplyAction="http://tempuri.org/IBaseServiceOf_Post_PostDto/UpdateResponse")]
        void Update(SimpleSocialNetwork.WebUI.PostServiceReference.PostDto entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseServiceOf_Post_PostDto/Update", ReplyAction="http://tempuri.org/IBaseServiceOf_Post_PostDto/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(SimpleSocialNetwork.WebUI.PostServiceReference.PostDto entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseServiceOf_Post_PostDto/GetById", ReplyAction="http://tempuri.org/IBaseServiceOf_Post_PostDto/GetByIdResponse")]
        SimpleSocialNetwork.WebUI.PostServiceReference.PostDto GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseServiceOf_Post_PostDto/GetById", ReplyAction="http://tempuri.org/IBaseServiceOf_Post_PostDto/GetByIdResponse")]
        System.Threading.Tasks.Task<SimpleSocialNetwork.WebUI.PostServiceReference.PostDto> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseServiceOf_Post_PostDto/GetAll", ReplyAction="http://tempuri.org/IBaseServiceOf_Post_PostDto/GetAllResponse")]
        System.Collections.Generic.List<SimpleSocialNetwork.WebUI.PostServiceReference.PostDto> GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseServiceOf_Post_PostDto/GetAll", ReplyAction="http://tempuri.org/IBaseServiceOf_Post_PostDto/GetAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SimpleSocialNetwork.WebUI.PostServiceReference.PostDto>> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostService/GetFriendsPostsByUserId", ReplyAction="http://tempuri.org/IPostService/GetFriendsPostsByUserIdResponse")]
        System.Collections.Generic.List<SimpleSocialNetwork.WebUI.PostServiceReference.PostDto> GetFriendsPostsByUserId(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostService/GetFriendsPostsByUserId", ReplyAction="http://tempuri.org/IPostService/GetFriendsPostsByUserIdResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SimpleSocialNetwork.WebUI.PostServiceReference.PostDto>> GetFriendsPostsByUserIdAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostService/GetPosts", ReplyAction="http://tempuri.org/IPostService/GetPostsResponse")]
        System.Collections.Generic.List<SimpleSocialNetwork.WebUI.PostServiceReference.PostDto> GetPosts(int authorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostService/GetPosts", ReplyAction="http://tempuri.org/IPostService/GetPostsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SimpleSocialNetwork.WebUI.PostServiceReference.PostDto>> GetPostsAsync(int authorId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPostServiceChannel : SimpleSocialNetwork.WebUI.PostServiceReference.IPostService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostServiceClient : System.ServiceModel.ClientBase<SimpleSocialNetwork.WebUI.PostServiceReference.IPostService>, SimpleSocialNetwork.WebUI.PostServiceReference.IPostService {
        
        public PostServiceClient() {
        }
        
        public PostServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PostServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Add(SimpleSocialNetwork.WebUI.PostServiceReference.PostDto entity) {
            base.Channel.Add(entity);
        }
        
        public System.Threading.Tasks.Task AddAsync(SimpleSocialNetwork.WebUI.PostServiceReference.PostDto entity) {
            return base.Channel.AddAsync(entity);
        }
        
        public void Remove(SimpleSocialNetwork.WebUI.PostServiceReference.PostDto entity) {
            base.Channel.Remove(entity);
        }
        
        public System.Threading.Tasks.Task RemoveAsync(SimpleSocialNetwork.WebUI.PostServiceReference.PostDto entity) {
            return base.Channel.RemoveAsync(entity);
        }
        
        public void RemoveById(int id) {
            base.Channel.RemoveById(id);
        }
        
        public System.Threading.Tasks.Task RemoveByIdAsync(int id) {
            return base.Channel.RemoveByIdAsync(id);
        }
        
        public void Update(SimpleSocialNetwork.WebUI.PostServiceReference.PostDto entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(SimpleSocialNetwork.WebUI.PostServiceReference.PostDto entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public SimpleSocialNetwork.WebUI.PostServiceReference.PostDto GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<SimpleSocialNetwork.WebUI.PostServiceReference.PostDto> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
        
        public System.Collections.Generic.List<SimpleSocialNetwork.WebUI.PostServiceReference.PostDto> GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SimpleSocialNetwork.WebUI.PostServiceReference.PostDto>> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public System.Collections.Generic.List<SimpleSocialNetwork.WebUI.PostServiceReference.PostDto> GetFriendsPostsByUserId(int userId) {
            return base.Channel.GetFriendsPostsByUserId(userId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SimpleSocialNetwork.WebUI.PostServiceReference.PostDto>> GetFriendsPostsByUserIdAsync(int userId) {
            return base.Channel.GetFriendsPostsByUserIdAsync(userId);
        }
        
        public System.Collections.Generic.List<SimpleSocialNetwork.WebUI.PostServiceReference.PostDto> GetPosts(int authorId) {
            return base.Channel.GetPosts(authorId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SimpleSocialNetwork.WebUI.PostServiceReference.PostDto>> GetPostsAsync(int authorId) {
            return base.Channel.GetPostsAsync(authorId);
        }
    }
}
